In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

## CREATING NUMPY ARRAYS

In [9]:
lis = [1,2,3]
nparr = np.array(lis)
nparr

array([1, 2, 3])

In [10]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(mat)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
start = 1
stop = 11
step = 2
size = 10
num = 8
n= 3

print(np.arange(start,stop,step))
print(np.linspace(start, stop, num))
print(np.zeros(size))
print(np.ones(size))
print(np.eye(n))

[1 3 5 7 9]
[ 1.          2.42857143  3.85714286  5.28571429  6.71428571  8.14285714
  9.57142857 11.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.random.rand(3,4))
print(np.random.randint(start, stop, size))

[[0.26679773 0.74165666 0.72540644 0.78046727]
 [0.16340107 0.50429797 0.76225887 0.39857345]
 [0.06619424 0.90007015 0.62852087 0.30701298]]
[ 1  4  6  3  9 10  3  6  2  6]


## INDEXING AND SELECTION IN NUMPY

In [13]:
arr = np.arange(0,11)
print(arr)
print(arr[0:5])
arr[0:5] = 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[100 100 100 100 100   5   6   7   8   9  10]


In [15]:
arr_copy = arr[0:5].copy()
#Making a copy of a numpy array
arr_copy

array([100, 100, 100, 100, 100])

In [17]:
arr = np.arange(1,11)
print(arr,'\n\n')
arr_bol = arr>4
arr_bol
# returns a numpy array of boolean values who satisfy the condition

[ 1  2  3  4  5  6  7  8  9 10] 




array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [18]:
arr_res = arr[arr_bol]
arr_res

array([ 5,  6,  7,  8,  9, 10])

## NUMPY OPERATIONS

In [20]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.argmax()

np.int64(8)

In [25]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
arr.sum()

np.int64(45)

In [27]:
arr.mean()

np.float64(5.0)

In [28]:
arr.var()

np.float64(6.666666666666667)

In [29]:
arr.std()

np.float64(2.581988897471611)

## PANDAS SERIES

In [30]:
Myindex = ["USA","INDIA","RUSSIA","GERMANY"]
Mydata = [1234,1253,1251,2355]
Myser = pd.Series(data = Mydata,index = Myindex)
Myser

USA        1234
INDIA      1253
RUSSIA     1251
GERMANY    2355
dtype: int64

In [31]:
dic= {"USA":1234,"INDIA":1253,"RUSSIA":1251,"GERMANY":2355}
Myser = pd.Series(dic)
Myser

USA        1234
INDIA      1253
RUSSIA     1251
GERMANY    2355
dtype: int64

In [33]:
dic2 = {"USA":1334,"INDIA":1153,"ENGLAND":1233,"GERMANY":2125}
Myser2 = pd.Series(dic2)

print(Myser + Myser2)

ENGLAND       NaN
GERMANY    4480.0
INDIA      2406.0
RUSSIA        NaN
USA        2568.0
dtype: float64


In [34]:
print(Myser.add(Myser2,fill_value = 0))

ENGLAND    1233.0
GERMANY    4480.0
INDIA      2406.0
RUSSIA     1251.0
USA        2568.0
dtype: float64


In [35]:
Myser.add(1000)

USA        2234
INDIA      2253
RUSSIA     2251
GERMANY    3355
dtype: int64

In [37]:
Myser.multiply(0.01)

USA        12.34
INDIA      12.53
RUSSIA     12.51
GERMANY    23.55
dtype: float64

## DATA FRAMES

In [39]:
lis = [1776,1867,1821,328,38,126,205,170,122]
mydata = np.array(lis)
mydata.shape = (3,3)
mydata = mydata.transpose()

myindex = ["USA","CANADA","MEXICO"]
mycolmns = ["Year","Pop","GDP"]

df = pd.DataFrame(data = mydata,index = myindex,columns = mycolmns)
print(df)

        Year  Pop  GDP
USA     1776  328  205
CANADA  1867   38  170
MEXICO  1821  126  122


In [114]:
df = pd.read_csv("car-sales.csv")

In [115]:
df.head()

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [116]:
df.tail()

Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64 
 3   Doors          10 non-null     int64 
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes


In [118]:
df.describe()

Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

### Working with columns

In [119]:
c = "Colour"
df[c]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: object

In [120]:
lis = ["Make","Odometer (KM)","Price"]
df[lis]

Make  Odometer (KM)       Price
0  Toyota         150043   $4,000.00
1   Honda          87899   $5,000.00
2  Toyota          32549   $7,000.00
3     BMW          11179  $22,000.00
4  Nissan         213095   $3,500.00
5  Toyota          99213   $4,500.00
6   Honda          45698   $7,500.00
7   Honda          54738   $7,000.00
8  Toyota          60000   $6,250.00
9  Nissan          31600   $9,700.00

In [121]:
df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [122]:
print(df.drop("Colour", axis=1))


     Make  Odometer (KM)  Doors       Price
0  Toyota         150043      4   $4,000.00
1   Honda          87899      4   $5,000.00
2  Toyota          32549      3   $7,000.00
3     BMW          11179      5  $22,000.00
4  Nissan         213095      4   $3,500.00
5  Toyota          99213      4   $4,500.00
6   Honda          45698      4   $7,500.00
7   Honda          54738      4   $7,000.00
8  Toyota          60000      4   $6,250.00
9  Nissan          31600      4   $9,700.00


### Working with rows

In [123]:
df

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [124]:
df.iloc[5]

Make                Toyota
Colour               Green
Odometer (KM)        99213
Doors                    4
Price            $4,500.00
Name: 5, dtype: object

In [125]:
ldf = df.set_index("Price")
ldf

Make Colour  Odometer (KM)  Doors
Price                                          
$4,000.00   Toyota  White         150043      4
$5,000.00    Honda    Red          87899      4
$7,000.00   Toyota   Blue          32549      3
$22,000.00     BMW  Black          11179      5
$3,500.00   Nissan  White         213095      4
$4,500.00   Toyota  Green          99213      4
$7,500.00    Honda   Blue          45698      4
$7,000.00    Honda   Blue          54738      4
$6,250.00   Toyota  White          60000      4
$9,700.00   Nissan  White          31600      4

In [126]:
ldf.loc['$5,000.00']

Make             Honda
Colour             Red
Odometer (KM)    87899
Doors                4
Name: $5,000.00, dtype: object

In [127]:
df.reset_index()

index    Make Colour  Odometer (KM)  Doors       Price
0      0  Toyota  White         150043      4   $4,000.00
1      1   Honda    Red          87899      4   $5,000.00
2      2  Toyota   Blue          32549      3   $7,000.00
3      3     BMW  Black          11179      5  $22,000.00
4      4  Nissan  White         213095      4   $3,500.00
5      5  Toyota  Green          99213      4   $4,500.00
6      6   Honda   Blue          45698      4   $7,500.00
7      7   Honda   Blue          54738      4   $7,000.00
8      8  Toyota  White          60000      4   $6,250.00
9      9  Nissan  White          31600      4   $9,700.00

### Conditional Filtering

In [128]:
df["Odometer (KM)"]>50000 #condition

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
8     True
9    False
Name: Odometer (KM), dtype: bool

In [129]:
df[df["Odometer (KM)"]>50000] #filtering based on condition

Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00

In [130]:
condn1 = df["Odometer (KM)"]>50000
condn2 = df["Doors"]==4
df[(condn1) & (condn2)] #using and operator for considering multiple conditions

Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00

In [131]:
options = ["Red","White"]
df["Colour"].isin(options)

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9     True
Name: Colour, dtype: bool

In [132]:
df[df["Colour"].isin(options)]

Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
4  Nissan  White         213095      4  $3,500.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

### Useful methods

In [133]:
def func(s):
    str = ""
    for i in range(len(s)):
        if (s[i].isdigit()):
            str+=s[i]
    return int(str)

str = "$1,000"
func(str)

1000

In [134]:
df["Cost"] = df["Price"].apply(func)
df["Cost"]

0     400000
1     500000
2     700000
3    2200000
4     350000
5     450000
6     750000
7     700000
8     625000
9     970000
Name: Cost, dtype: int64

In [135]:
df

Make Colour  Odometer (KM)  Doors       Price     Cost
0  Toyota  White         150043      4   $4,000.00   400000
1   Honda    Red          87899      4   $5,000.00   500000
2  Toyota   Blue          32549      3   $7,000.00   700000
3     BMW  Black          11179      5  $22,000.00  2200000
4  Nissan  White         213095      4   $3,500.00   350000
5  Toyota  Green          99213      4   $4,500.00   450000
6   Honda   Blue          45698      4   $7,500.00   750000
7   Honda   Blue          54738      4   $7,000.00   700000
8  Toyota  White          60000      4   $6,250.00   625000
9  Nissan  White          31600      4   $9,700.00   970000

In [136]:
df.sort_values("Cost")

Make Colour  Odometer (KM)  Doors       Price     Cost
4  Nissan  White         213095      4   $3,500.00   350000
0  Toyota  White         150043      4   $4,000.00   400000
5  Toyota  Green          99213      4   $4,500.00   450000
1   Honda    Red          87899      4   $5,000.00   500000
8  Toyota  White          60000      4   $6,250.00   625000
7   Honda   Blue          54738      4   $7,000.00   700000
2  Toyota   Blue          32549      3   $7,000.00   700000
6   Honda   Blue          45698      4   $7,500.00   750000
9  Nissan  White          31600      4   $9,700.00   970000
3     BMW  Black          11179      5  $22,000.00  2200000

In [137]:
df["Colour"].value_counts()

Colour
White    4
Blue     3
Red      1
Black    1
Green    1
Name: count, dtype: int64

In [139]:
df["Colour"].unique()

array(['White', 'Red', 'Blue', 'Black', 'Green'], dtype=object)

### MATPLOTLIB